name: face_app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cmake
  - dlib=19.24
  - numpy
  - pandas
  - pip
  - pip:
    - streamlit
    - face-recognition
    - opencv-python-headless
    - faiss-cpu