name: face_app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cmake
  - dlib
  - pip
  - pip:
    - streamlit
    - face-recognition
    - opencv-python-headless
    - faiss-cpu
    - pandas
    - numpy